Handle email without a sender name
ibmresilient/resilient-scripts pull request #3
Opened 2021-04-19 13:59 UTC by SeanEmac

2021-04-19 14:06 UTC, Bastian-Graebener requested changes
One request

2021-04-19 14:06 UTC, Bastian-Graebener commented on python3/emailmessage/email_sample_script.py
> +        if hasattr(emailmessage.sender, "name"):
I think you still want to check that name is not none.
```suggestion
        if hasattr(emailmessage.sender, "name") and emailmessage.sender.name is not None:
```

2021-04-19 15:32 UTC, Bastian-Graebener approved these changes
LGTM

2021-04-20 19:21 UTC, mscherfling approved these changes

2021-04-20 19:22 UTC, merged